// Generates an email-compatible HTML report (table-based, inline styles — works in Gmail/Outlook)
import { writeFileSync } from 'fs';

const OUTPUT = 'report.html';

export function generateReport(jobs) {
  const date = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

  const cards = jobs.length
    ? jobs.map((job) => `
      <tr><td style="padding:0 0 12px 0;">
        <table width="100%" cellpadding="0" cellspacing="0" style="background:#FFFFFF;border:1px solid #E2E8F0;border-radius:12px;overflow:hidden;">
          <tr><td style="padding:20px 24px 0;">
            <table width="100%" cellpadding="0" cellspacing="0">
              <tr>
                <td style="font-size:16px;font-weight:700;color:#0F172A;line-height:1.3;font-family:'Segoe UI',system-ui,sans-serif;">${esc(job.title)}</td>
                ${job.salary ? `<td align="right" style="white-space:nowrap;vertical-align:top;padding-left:12px;">
                  <span style="background:#EEF2FF;color:#4F46E5;border:1px solid #C7D2FE;border-radius:6px;padding:4px 10px;font-size:12px;font-weight:700;font-family:'Segoe UI',system-ui,sans-serif;">${esc(job.salary)}</span>
                </td>` : ''}
              </tr>
            </table>
          </td></tr>
          <tr><td style="padding:6px 24px 0;font-size:14px;font-weight:500;color:#64748B;font-family:'Segoe UI',system-ui,sans-serif;">${esc(job.company)}</td></tr>
          <tr><td style="padding:10px 24px 0;">
            ${job.tags.slice(0, 6).map((t) =>
              `<span style="display:inline-block;background:#F8FAFC;border:1px solid #E2E8F0;border-radius:4px;padding:3px 8px;font-size:11px;color:#475569;font-weight:500;margin:0 4px 4px 0;font-family:'Segoe UI',system-ui,sans-serif;">${esc(t)}</span>`
            ).join('')}
          </td></tr>
          <tr><td style="padding:12px 24px 16px;">
            <table width="100%" cellpadding="0" cellspacing="0" style="border-top:1px solid #F1F5F9;padding-top:12px;">
              <tr>
                <td style="font-size:12px;color:#94A3B8;padding-top:10px;font-family:'Segoe UI',system-ui,sans-serif;">${esc(job.date)}</td>
                <td align="right" style="padding-top:10px;">
                  <a href="${esc(job.url)}" target="_blank" rel="noopener" style="background:#4F46E5;color:#ffffff;text-decoration:none;font-weight:700;font-size:13px;padding:8px 18px;border-radius:7px;display:inline-block;font-family:'Segoe UI',system-ui,sans-serif;">View Job →</a>
                </td>
              </tr>
            </table>
          </td></tr>
        </table>
      </td></tr>`).join('')
    : '<tr><td style="padding:40px 0;text-align:center;color:#94A3B8;font-size:16px;font-family:\'Segoe UI\',system-ui,sans-serif;">No web developer jobs found in this period.</td></tr>';

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Job Market Report — ${date}</title>
</head>
<body style="margin:0;padding:0;background:#F1F5F9;font-family:'Segoe UI',system-ui,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#F1F5F9;">
    <tr><td align="center" style="padding:32px 16px;">
      <table width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;">

        <!-- Header -->
        <tr><td style="padding:0 0 8px;">
          <p style="margin:0;font-size:10px;letter-spacing:2.5px;color:#4F46E5;text-transform:uppercase;font-weight:700;font-family:'Segoe UI',system-ui,sans-serif;">JOB MARKET MONITOR</p>
        </td></tr>
        <tr><td style="padding:0 0 6px;">
          <h1 style="margin:0;font-size:28px;font-weight:800;color:#0F172A;line-height:1.2;font-family:'Segoe UI',system-ui,sans-serif;">Remote <span style="color:#4F46E5;">Web Developer</span> Jobs</h1>
        </td></tr>
        <tr><td style="padding:0 0 20px;font-size:13px;color:#64748B;font-family:'Segoe UI',system-ui,sans-serif;">
          Date: <strong style="color:#4F46E5;">${date}</strong> &nbsp;&nbsp;&nbsp; Last 7d: <strong style="color:#4F46E5;">${jobs.length} listing${jobs.length !== 1 ? 's' : ''}</strong>
        </td></tr>

        <!-- Divider -->
        <tr><td style="padding:0 0 20px;"><div style="height:1px;background:#E2E8F0;"></div></td></tr>

        <!-- Cards -->
        ${cards}

        <!-- Footer -->
        <tr><td style="padding:32px 0 0;text-align:center;font-size:11px;color:#CBD5E1;font-family:'Segoe UI',system-ui,sans-serif;">
          Generated by job-market-monitor &bull; Source: RemoteOK API
        </td></tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`;

  writeFileSync(OUTPUT, html, 'utf8');
  console.log(`Report saved → ${OUTPUT} (${jobs.length} job${jobs.length !== 1 ? 's' : ''})`);
  return html;
}

function esc(str) {
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
